server:
  port: 8190
  servlet:
    context-path: /march-market-cart
integrations:
  product-service:
    url: http://localhost:8189/march-market-core/
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000

